---
- become: yes
  block: 
  
  - name: Reload daemon
    ansible.builtin.systemd:
      daemon_reload: yes
    ignore_errors: "{{ node_exporter.ignore_systemd_errors }}"

  - name: Restart node_exporter
    ansible.builtin.systemd:
      name: node_exporter.service
      state: restarted
    ignore_errors: "{{ node_exporter.ignore_systemd_errors }}"